#! /bin/bash

# SOURCE : https://funprojects.blog/2022/06/12/apps-and-scripts-in-the-system-tray/

BINARY_NAME=$(cat ./BINARY_NAME)
VERSION=$(cat ./VERSION)
RECENT_LOG_LINES_COUNT=$(wc --lines ~/.config/${BINARY_NAME}-${VERSION}/targets | awk '{print $1}')
ABOUT_CONTENT=$(cat ~/.local/share/${BINARY_NAME}-${VERSION}/about)


yad --notification --image="appointment-new-symbolic" \
 --command="yad --text='$ABOUT_CONTENT' --title='${BINARY_NAME}' --geometry=600x100+600+200 --button=OK" \
 --menu="See Stats! xterm -bg white -fg black -hold -geometry 100x30+600+200 -fa Monospace -fs 10 -T '${BINARY_NAME} logs' -e 'watch tail --lines $RECENT_LOG_LINES_COUNT ~/.local/share/${BINARY_NAME}-${VERSION}/logs' \
       |Reload Config ! bash -c 'kill -SIGUSR1 $(pgrep ${BINARY_NAME}) && killall ${BINARY_NAME}-applet && ${BINARY_NAME}-applet' \
       |Quit ! killall ${BINARY_NAME}-applet " \
 --text="${BINARY_NAME} applet"